Repository 2S2C-14/2S2C-14, pull requests merged in 2025-08, with the labels that each got.

#1 Access, airlocks, and radio for mapping
  Resources/Locale/en-US/_2S2C/radio.ftl
  Resources/Prototypes/_2S2C/access.yml
  Resources/Prototypes/_2S2C/airlocks.yml
  Resources/Prototypes/_2S2C/encryption_keys.yml
  Resources/Prototypes/_2S2C/headsets.yml
  Resources/Prototypes/_2S2C/radio_channels.yml
  Resources/Prototypes/_2S2C/telecomms.yml
Labels: S: Untriaged, size/M, S: Needs Review

#5 annotated access and addec nt/syndi id console variants
  Resources/Prototypes/_2S2C/access.yml
  Resources/Prototypes/_2S2C/computers.yml
Labels: size/M, S: Needs Review, T:New Feature, D3:Low, P2:Raised, Changes: No C#

#7 new role mapping points
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Prototypes/_2S2C/jobs.yml
  Resources/Prototypes/_2S2C/roles/assistant.yml
  Resources/Prototypes/_2S2C/roles/captain.yml
  Resources/Prototypes/_2S2C/roles/chief_of_operations.yml
  Resources/Prototypes/_2S2C/roles/chief_technician.yml
  Resources/Prototypes/_2S2C/roles/clown.yml
  Resources/Prototypes/_2S2C/roles/departments.yml
  Resources/Prototypes/_2S2C/roles/janitor.yml
  Resources/Prototypes/_2S2C/roles/mime.yml
  Resources/Prototypes/_2S2C/roles/musician.yml
  Resources/Prototypes/_2S2C/roles/operative.yml
  Resources/Prototypes/_2S2C/roles/service.yml
  Resources/Prototypes/_2S2C/roles/supplier.yml
  Resources/Prototypes/_2S2C/roles/technician.yml
  Resources/Prototypes/_2S2C/roles/trade_station_agent.yml
  Resources/Textures/Markers/jobs.rsi/blue.png
  Resources/Textures/Markers/jobs.rsi/meta.json
  Resources/Textures/Markers/jobs.rsi/red.png
Labels: size/M, S: Needs Review, D3:Low, P2:Raised, Changes: No C#

#10 added glass airlock variants
  Resources/Prototypes/_2S2C/airlocks.yml
Labels: S: Untriaged, size/M, S: Needs Review

#8 locale and loadout framework
  Resources/Locale/en-US/_2S2C/job-names.ftl
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Prototypes/_2S2C/roles/assistant.yml
  Resources/Prototypes/_2S2C/roles/loadout_groups.yml
  Resources/Prototypes/_2S2C/roles/play_time_tracker.yml
  Resources/Prototypes/_2S2C/roles/role_loadouts.yml
Labels: S: Untriaged, size/M, S: Needs Review
